- !policy
  id: frontend
  body:
    - &frontendsecrets
      - !variable
        id: nginx_user

      - !variable
        id: nginx_pwd

      - !variable
        id: nginx_address

    - !permit
      role: !layer /conjur/authn-k8s/k8s-follower/apps
      resource: *frontendsecrets
      privileges:
       - execute

    - !permit
      role: !layer /conjur/authn-k8s/okd-follower/apps
      resource: *frontendsecrets
      privileges:
       - execute

    - !permit
       role: !layer /cicd/jenkins
       resource: *frontendsecrets
       privileges:
        - execute
        - read

    - !permit
      role: !layer /cicd/ansible
      resource: *frontendsecrets
      privileges:
       - execute
       - read

- !policy
  id: backend
  body:
    - &backendsecrets
      - !variable
        id: postgres_user

      - !variable
        id: postgres_pwd

      - !variable
        id: postgres_address

    - !permit
      role: !layer /conjur/authn-k8s/k8s-follower/apps
      resource: *backendsecrets
      privileges:
       - execute

    - !permit
      role: !layer /conjur/authn-k8s/okd-follower/apps
      resource: *backendsecrets
      privileges:
       - execute

- !policy
  id: scm
  body:
    - &scmjenkinsvariables
      - !variable
        id: jenkins_gitlabusername

      - !variable
        id: jenkins_gitlabpassword

    - &scmansiblevariables
      - !variable
        id: ansible_gitlabusername

      - !variable
        id: ansible_gitlabpassword

    - !permit
      role: !layer /cicd/jenkins
      resource: *scmjenkinsvariables
      privileges:
       - execute

    - !permit
      role: !layer /cicd/ansible
      resource: *scmansiblevariables
      privileges:
       - execute

- !policy
  id: artifactory
  body:
    - &artifactoryjenkinsvariables
      - !variable
        id: jenkins_artifactoryusername

      - !variable
        id: jenkins_artifactorypassword

    - &artifactoryansiblevariables
      - !variable
        id: ansible_artifactorypassword

      - !variable
        id: ansible_artifactoryusername

    - !permit
      role: !layer /cicd/jenkins
      resource: *artifactoryjenkinsvariables
      privileges:
       - execute
       - read

    - !permit
      role: !layer /cicd/ansible
      resource: *artifactoryansiblevariables
      privileges:
       - execute
       - read

- !policy
  id: ansible_access
  body:
    - &ansible_accessvariables
      - !variable
        id: jenkins_ansibleusername

      - !variable
        id: jenkins_ansiblepassword

    - !permit
      role: !layer /cicd/jenkins
      resource: *ansible_accessvariables
      privileges:
       - read
       - execute

- !policy
  id: sshkeys
  body:
    - !variable
      id: jenkins_privatesshkey

    - !permit
      role: !layer /cicd/jenkins
      resource: !variable jenkins_privatesshkey
      privileges:
        - read
        - execute

- !policy
  id: policy_updates
  body:
    - &policyvariables
      - !variable
        id: username
      
      - !variable
        id: apikey
    
    - !permit
      role: !layer /cicd/jenkins
      resource: *policyvariables
      privileges:
        - read
        - execute
